server:
  port: 8081

cas:
  server:
    prefix: https://cas.nameicc.org:8443/cas
    login: ${cas.server.prefix}/login
    logout: ${cas.server.prefix}/logout

  client:
    prefix: http://client.cas.nameicc.org:${server.port}
    login: ${cas.client.prefix}/login/cas
    logoutRelative: /logout/cas
    logout: ${cas.client.prefix}${cas.client.logoutRelative}

spring:
  # 数据库配置
  datasource:
    url: jdbc:mysql://localhost:3306/spring_security?characterEncoding=UTF-8
    username: root
    password: root

# mybatis配置
mybatis:
  mapper-locations: classpath:mapper/*.xml